name: kumori
description: "🌙 Kumori - Персональный финансовый менеджер на Flutter. Современное приложение для учета доходов и расходов с красивым интерфейсом и умной группировкой транзакций."

publish_to: 'none'


version: 1.0.0+2

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.20.2
  shared_preferences: ^2.2.2

  
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/logo/logo.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/logo.png"